on: [push]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run test-storybook
        env:
          SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}